import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Numbers",
  description: "Generated by Tiffany Sharpe",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-100">
          <nav className="flex justify-center w-100 bg-blue-300">
                     
            <Link
              className="m-1 text-white hover:text-purple-500"
              href="/Home">
              Home
            </Link>   
                
          </nav>
        </header>
        {children}
        <footer className="text-center mt-7">&copy; Rolling Dice with Tiffany</footer>
      </body>
    </html>
  );
}